name: chatops
on:
  issue_comment:
    types: [created]

jobs:
  default:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}
          installation_id: ${{ secrets.GH_INSTALLATION_ID }}

      - name: "Handle common commands"
        uses: ugns/actions/github/slash-command-dispatch@1.0.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ugns/actions
          commands: rebuild-readme, terraform-fmt
          permission: triage
          issue-type: pull-request

  test:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: "Checkout commit"
        uses: actions/checkout@v3

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}
          installation_id: ${{ secrets.GH_INSTALLATION_ID }}

      - name: "Run tests"
        uses: ugns/actions/github/slash-command-dispatch@1.0.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ugns/actions
          commands: test
          permission: triage
          issue-type: pull-request
          reactions: false


